name: Deploy app to Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-site:
    name: Deploy Site
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v2

    - name: 'Deploy Site to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: Site/ 